# Generated by Django 3.2.12 on 2022-04-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100, unique=True, verbose_name='Identificação')),
                ('description', models.CharField(max_length=100, verbose_name='Descrição')),
                ('url', models.URLField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('updated', models.DateField(auto_now=True, verbose_name='atualizado')),
            ],
            options={
                'ordering': ['key'],
            },
        ),
    ]
